### ISSUE TITLE
Optional support for `mode-line-buffer-identification`

### ISSUE THREAD

**Issue by zevlg** [TatriX/good-line#1]
Some modes (such as chat buffer mode in [telega.el](https://github.com/zevlg/telega.el)) uses `mode-line-buffer-identification` to show additional state information.  It would be nice if `good-line` can be customized to show it in some buffers.

Thanks

**Comment by TatriX** [comment]
Sure, I'll take a look.
If people are actually using this package, I should probably put it on melpa?

**Comment by zevlg** [comment]
I know people who switched to good-line because of unfixed issues in mood-line

I’m also considering using it, but `mode-line-buffer-identification` is essential for me
