### ISSUE TITLE
mu4e segment

### ISSUE THREAD

**Issue by arkhan** [TatriX/good-line#3]
Regards,
Great job with this.
You could add a segment for mu4e
Thank you.

**Comment by TatriX** [comment]
I think `(mu4e-alert-enable-mode-line-display)` should just work, isn't it?

**Comment by arkhan** [comment]
It does work but it is generic and shows the icon that looks like the status bar.

**good-line**
![img-2019-09-09-120419](https://user-images.githubusercontent.com/3141865/64551412-94b41e80-d2fa-11e9-939d-94ec566bd021.png)

**doom-modeline**
![img-2019-09-09-120230](https://user-images.githubusercontent.com/3141865/64551424-9bdb2c80-d2fa-11e9-8be2-77944acce164.png)

There is the difference

regards

**Comment by TatriX** [comment]
Sorry, I don't really understand where to look at. Could you please explain a bit more, what exactly do you want?
